### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by under-score** [stefan-loewe/polyphase-meter#1]
Followed the advice at the `[forum](https://www.photovoltaikforum.com/wissen/entry/52-auslesen-von-stromverbrauch-stromproduktion-strombezug-von-stromz%C3%A4hler-logarex-l/)` as I have the same meter.

Unfortunately the demo script stops indefinitely at
`$reading = $connector->read();`
without any error message

![Bildschirmfoto 2022-01-23 um 10 04 32](https://user-images.githubusercontent.com/2796454/150671882-8b8fc78d-8766-4f22-bd58-192ea32e45eb.jpg)

**Comment by stefan-loewe** [comment]
Hey, thanks for your interest in this (hobby) project.

Do you get any output if you do `cat /dev/ttyUSB0` or `sudo cat /dev/ttyUSB0`?

**Comment by under-score** [comment]
Yes, but only after sending
`\x2F\x3F\x21\x0D\x0A`
My response string is also slightly different than yours
`/LOG4LK13BD102015`
while your script unfortunately does not work even after changing it

**Comment by stefan-loewe** [comment]
Okay, please do me a favor and post the exact command you send and the respective responses you get when reading via command line, i..e, what you have to do and get prior to reading from `/dev/ttyUSB0` via `cat`.

If `cat` works, so must `php` ... in theory ;)

**Comment by under-score** [comment]
Yes, in theory ;-)  `cat` tells me
```
/LOG4LK13BD102015
C.1.0(06082796)
0.0.0(001LOG0006082796)
F.F(0000)
1.8.0(014897.700*kWh)
C.7.1(00000001)
C.7.2(00000002)
C.7.3(00000001)
0.2.1(ver.02, 130314, 41BD)
C14897.7 0
```
As also another php lib did not work, I decided for
```
shell_exec("stty -F /dev/ttyUSB0 300 -parodd cs7 -cstopb parenb -ixoff -crtscts -hupcl -ixon -opost -onlcr -isig -icanon -iexten -echo -echoe -echoctl -echoke");
shell_exec("echo -n -e '\x2F\x3F\x21\x0D\x0A' > /dev/ttyUSB0");
$out = shell_exec("timeout 10s cat /dev/ttyUSB0");
sleep(11);
```
which works now for several days via `cron`.

**Comment by stefan-loewe** [comment]
I can only assume something is blocking the read, maybe its your (custom) PHP version, maybe related to your OS ... from here, I only can guess. I have this solution working now for about a year, rock solid.
But good to know you have a working solution, this is what counts in the end.

I will close this now.

Thanks for your interest and happy monitoring!
